#!/bin/env bash
###################################################################
#
# The World of Numbers
######################
#
# Given two integers, X and Y, find their sum, difference, product
# and quotient.
####################################################################

read one
read two

echo $(($one + $two))
echo $(($one - $two))
echo $(($one * $two))
echo $(($one / $two))
